# Generated by Django 3.2.3 on 2021-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=50)),
                ('plantAlt', models.CharField(blank=True, default='', max_length=255)),
                ('env', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255)),
                ('plantImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
