# Generated by Django 3.2.3 on 2021-06-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plantImg',
        ),
    ]
