# Generated by Django 3.2.3 on 2021-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0002_remove_plant_plantimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Hard', max_length=50),
            preserve_default=False,
        ),
    ]
