# Generated by Django 3.2.3 on 2021-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0004_alter_plant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Easy', max_length=50),
        ),
    ]
