# Generated by Django 3.2.3 on 2021-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0006_alter_plant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='level',
            field=models.CharField(choices=[('0', 'Easy'), ('1', 'Medium'), ('2', 'Hard')], max_length=50),
        ),
    ]
