# Generated by Django 3.2.3 on 2021-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0007_alter_plant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
