# Generated by Django 3.2.3 on 2021-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0011_alter_plant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='level',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
