# Generated by Django 3.2.3 on 2021-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0012_alter_plant_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
