# Generated by Django 3.2.3 on 2021-06-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0014_plant_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='poster',
        ),
    ]
