# Generated by Django 3.2.3 on 2021-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_alias'),
        ('plantApp', '0017_alter_plant_plantimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='users_fav',
            field=models.ManyToManyField(related_name='fav_plants', to='login_app.User'),
        ),
    ]
