# Generated by Django 3.2.3 on 2021-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0020_alter_plant_plantimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantImg',
            field=models.FileField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
