# Generated by Django 3.2.3 on 2021-06-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0025_alter_plant_plantimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantImg',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
